@startuml dictionary
class DictProducer  {
	- _files : vector<string>
	- _dict : vector<pair<string,int>>
	- _index: map<string,set<int>>
	- _cuttor : SplitTool
	+ DictProducer(string, tool)
	+ buildEnDict(): void
	+ buildCnDict(): void
	+ createIndex(): void
	+ store() void
}

class SplitTool {
	+ {abstract}cut(): vector<string>
}

class SplitToolCppJieba {
	+ cut(): vector<string>
}

class Configuration {}

DictProducer --> SplitTool
DictProducer ..> Configuration 
SplitToolCppJieba --|> SplitTool
SplitToolCppJieba ..> Configuration
@enduml